# Generated by Django 5.1.3 on 2024-11-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='updated_at',
            new_name='date_modified',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='created_at',
            new_name='date_uploaded',
        ),
        migrations.AddField(
            model_name='asset',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
