# Generated by Django 5.2.5 on 2025-09-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
