# Generated by Django 5.2 on 2025-08-25 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0004_auto_20250825_2253'),
    ]

    operations = [
        # This operation was moved to after field type change and duplicate cleanup
    ]
