# Generated by Django 5.2 on 2025-08-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_sharelink_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharelink',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='object_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='sharelink',
            unique_together={('content_type', 'object_id')},
        ),
    ]
