# Generated by Django 5.2.5 on 2025-09-11 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_workspace_admin_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the asset was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='s3_deletion_scheduled_at',
            field=models.DateTimeField(blank=True, help_text='When S3 deletion was scheduled', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='s3_files_deleted',
            field=models.BooleanField(default=False, help_text='Whether S3 files have been permanently deleted'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['workspace', 'deleted_at'], name='main_asset_workspa_8866d4_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['deleted_at'], name='main_asset_deleted_f108ca_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['s3_deletion_scheduled_at'], name='main_asset_s3_dele_4d7459_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['workspace', 'file_type'], name='main_asset_workspa_7fff23_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['date_uploaded'], name='main_asset_date_up_93b0fd_idx'),
        ),
    ]
