# Generated by Django 5.2.5 on 2025-09-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_asset_deleted_at_asset_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetanalysis',
            name='color_search_text',
            field=models.TextField(blank=True, help_text='Flattened color data for searching'),
        ),
        migrations.AddField(
            model_name='assetanalysis',
            name='dominant_colors',
            field=models.JSONField(default=list, help_text='Dominant colors with percentages'),
        ),
        migrations.AddField(
            model_name='assetanalysis',
            name='image_properties',
            field=models.JSONField(default=dict, help_text='Image quality metrics and color analysis'),
        ),
        migrations.AddField(
            model_name='assetanalysis',
            name='simplified_colors',
            field=models.JSONField(default=list, help_text='Simplified color names for easy filtering'),
        ),
    ]
