# Generated by Django 5.2 on 2025-08-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_sharelink_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharelink',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='sharelink',
            name='current_uses',
        ),
        migrations.RemoveField(
            model_name='sharelink',
            name='max_uses',
        ),
    ]
