# Generated by Django 5.2.5 on 2025-09-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_assetanalysis_color_search_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetanalysis',
            name='altitude',
            field=models.FloatField(blank=True, help_text='GPS altitude in meters', null=True),
        ),
        migrations.AddField(
            model_name='assetanalysis',
            name='aperture',
            field=models.CharField(blank=True, help_text='F-stop aperture value', max_length=20),
        ),
        migrations.AddField(
            model_name='assetanalysis',
            name='camera_make',
            field=models.CharField(blank=True, help_text='Camera manufacturer (e.g., Apple, Canon)', max_length=100),
        ),
        migrations.AddField(
            model_name='assetanalysis',
            name='camera_model',
            field=models.CharField(blank=True, help_text='Camera model (e.g., iPhone 11 Pro Max)', max_length=200),
        ),
        migrations.AddField(
            model_name='assetanalysis',
            name='date_taken',
            field=models.DateTimeField(blank=True, help_text='When the photo was originally taken', null=True),
        ),
        migrations.AddField(
            model_name='assetanalysis',
            name='exif_data',
            field=models.JSONField(default=dict, help_text='Complete EXIF data from image'),
        ),
        migrations.AddField(
            model_name='assetanalysis',
            name='exif_search_text',
            field=models.TextField(blank=True, help_text='Flattened EXIF data for searching'),
        ),
        migrations.AddField(
            model_name='assetanalysis',
            name='exposure_time',
            field=models.CharField(blank=True, help_text='Shutter speed/exposure time', max_length=50),
        ),
        migrations.AddField(
            model_name='assetanalysis',
            name='focal_length',
            field=models.CharField(blank=True, help_text='Focal length in mm', max_length=20),
        ),
        migrations.AddField(
            model_name='assetanalysis',
            name='iso_speed',
            field=models.IntegerField(blank=True, help_text='ISO speed rating', null=True),
        ),
        migrations.AddField(
            model_name='assetanalysis',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS latitude coordinate', null=True),
        ),
        migrations.AddField(
            model_name='assetanalysis',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS longitude coordinate', null=True),
        ),
    ]
