# Generated by Django 5.1.3 on 2024-12-16 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_paddle_billing', '0003_discount'),
        ('main', '0005_alter_workspaceinvitation_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspaces', to='django_paddle_billing.subscription'),
        ),
    ]
