# Generated by Django 5.2 on 2025-08-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20250826_0900'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharelink',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='allow_commenting',
            field=models.BooleanField(default=True, help_text='Allow shared users to add comments'),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='allow_editing_custom_fields',
            field=models.BooleanField(default=False, help_text='Allow shared users to edit custom fields'),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='show_comments',
            field=models.BooleanField(default=True, help_text='Show existing comments to shared users'),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='show_custom_fields',
            field=models.BooleanField(default=True, help_text='Show custom fields to shared users'),
        ),
    ]
