# Generated by Django 5.2 on 2025-08-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_sharelink_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharelink',
            name='permission',
        ),
    ]
