# Generated by Django 5.1.3 on 2024-12-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_paddle_billing', '0003_discount'),
        ('main', '0006_workspace_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='subscription',
        ),
        migrations.AddField(
            model_name='workspace',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='workspaces', to='django_paddle_billing.subscription'),
        ),
    ]
