# Generated by Django 5.2.5 on 2025-08-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_sharelink_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='allow_commenting',
            field=models.BooleanField(default=False, help_text='Allow shared users to add comments'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='show_comments',
            field=models.BooleanField(default=False, help_text='Show existing comments to shared users'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='show_custom_fields',
            field=models.BooleanField(default=False, help_text='Show custom fields to shared users'),
        ),
    ]
