# Generated by Django 5.2 on 2025-08-26 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0008_alter_sharelink_allow_commenting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='board',
            field=models.ForeignKey(blank=True, help_text='Board context for asset sharing. Required for assets, optional for boards/collections.', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.board'),
        ),
        migrations.AlterUniqueTogether(
            name='sharelink',
            unique_together={('content_type', 'object_id', 'board')},
        ),
    ]
