# Generated by Django 5.1.6 on 2025-03-24 14:40

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_board_boardasset_asset_boards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(max_length=500, upload_to=main.models.workspace_asset_path),
        ),
    ]
