# Generated by Django 5.2 on 2025-08-26 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_sharelink_board_alter_sharelink_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='allow_downloads',
            field=models.BooleanField(default=True, help_text='Allow shared users to download the content'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='board',
            field=models.ForeignKey(blank=True, help_text='Board context for sharing. Null = global context, Board = board-specific context.', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.board'),
        ),
    ]
