# Generated by Django 5.1.6 on 2025-03-26 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_board_options_board_updated_at_alter_board_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.board'),
        ),
    ]
