# Generated by Django 5.2 on 2025-08-26 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sharelink_allow_downloads_alter_sharelink_board'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_email',
            field=models.EmailField(blank=True, help_text='Email for anonymous users', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(blank=True, help_text='Display name for anonymous users', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='True if this comment was made by an anonymous user'),
        ),
        migrations.CreateModel(
            name='CustomFieldEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_email', models.EmailField(blank=True, help_text='Email for anonymous editors', max_length=254, null=True)),
                ('editor_name', models.CharField(blank=True, help_text='Display name for anonymous editors', max_length=255, null=True)),
                ('field_type', models.CharField(help_text='Type of field that was edited', max_length=20)),
                ('old_value', models.JSONField(blank=True, help_text='Previous value before edit (null for new values)', null=True)),
                ('new_value', models.JSONField(help_text='New value after edit')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('field_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='main.customfieldvalue')),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_edits', to='main.sharelink')),
            ],
            options={
                'ordering': ['-edited_at'],
                'indexes': [models.Index(fields=['field_value', 'edited_at'], name='main_custom_field_v_edc099_idx'), models.Index(fields=['share_link', 'edited_at'], name='main_custom_share_l_f03f83_idx'), models.Index(fields=['editor', 'edited_at'], name='main_custom_editor__6696d4_idx')],
            },
        ),
    ]
