# Generated by Django 5.1.6 on 2025-03-28 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_board_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, default='Click to edit description'),
        ),
        migrations.CreateModel(
            name='AssetAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_analysis', models.JSONField(default=dict)),
                ('labels', models.JSONField(default=list, help_text='AI-detected objects/scenes')),
                ('moderation_labels', models.JSONField(default=list, help_text='Content moderation results')),
                ('searchable_text', models.TextField(blank=True, help_text='Flattened text of all labels for searching')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='main.asset')),
            ],
            options={
                'verbose_name_plural': 'Asset analyses',
            },
        ),
    ]
