# Generated by Django 5.2 on 2025-08-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_comment_author_email_comment_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this share link is active and accessible'),
        ),
    ]
