# Generated by Django 5.1.6 on 2025-03-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_board_description_assetanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
