# Generated by Django 5.2 on 2025-05-13 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_asset_date_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(related_name='workspaces', through='main.WorkspaceMember', through_fields=('workspace', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
