# Generated by Django 5.2 on 2025-05-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_asset_favorite_alter_workspace_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
