# Generated by Django 5.2 on 2025-05-22 11:27

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_board_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='board',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which to display this board'),
        ),
        migrations.AddField(
            model_name='board',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.board'),
        ),
    ]
