# Generated by Django 5.2 on 2025-06-04 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0016_alter_board_options_board_level_board_lft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('SINGLE_SELECT', 'Single Select'), ('MULTI_SELECT', 'Multi Select'), ('TEXT', 'Plain Text'), ('DATE', 'Date')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='main.workspace')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('workspace', 'title')},
            },
        ),
        migrations.CreateModel(
            name='CustomFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.customfield')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('field', 'label')},
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('text_value', models.TextField(blank=True, null=True)),
                ('date_value', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customfield')),
                ('multi_options', models.ManyToManyField(blank=True, related_name='multi_field_values', to='main.customfieldoption')),
                ('option_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_values', to='main.customfieldoption')),
            ],
            options={
                'unique_together': {('field', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='AIActionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('spelling_grammar', 'Spelling and Grammar Check'), ('color_contrast', 'Color Contrast Analysis'), ('image_quality', 'Image Quality Check'), ('image_artifacts', 'Image Artifacts Detection')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('result', models.JSONField(default=dict, help_text='Results of the AI analysis')),
                ('error_message', models.TextField(blank=True, help_text='Error message if the action failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('field_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='main.customfieldvalue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldOptionAIAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('spelling_grammar', 'Spelling and Grammar Check'), ('color_contrast', 'Color Contrast Analysis'), ('image_quality', 'Image Quality Check'), ('image_artifacts', 'Image Artifacts Detection')], max_length=50)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this action is currently enabled for this option')),
                ('configuration', models.JSONField(default=dict, help_text='Configuration settings for this action')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_action_configs', to='main.customfieldoption')),
            ],
            options={
                'unique_together': {('option', 'action')},
            },
        ),
    ]
