# Generated by Django 5.2 on 2025-06-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_boardfollower_comment_emailbatch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='channel',
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_enabled',
            field=models.BooleanField(default=True, help_text='Receive email notifications'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='in_app_enabled',
            field=models.BooleanField(default=True, help_text='Receive in-app notifications'),
        ),
    ]
