# Generated by Django 5.2 on 2025-06-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_notificationpreference_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='annotation_type',
            field=models.CharField(choices=[('NONE', 'No annotation'), ('POINT', 'Point annotation'), ('AREA', 'Area annotation')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
