# Generated by Django 5.2 on 2025-06-16 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_notificationpreference_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boardfollower',
            name='auto_followed',
            field=models.BooleanField(default=False, help_text='Whether this was automatically created by the system'),
        ),
        migrations.CreateModel(
            name='BoardExplicitUnfollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unfollowed_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explicit_unfollows', to='main.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_explicit_unfollows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'board'], name='main_boarde_user_id_fdac70_idx')],
                'unique_together': {('user', 'board')},
            },
        ),
    ]
