# Generated by Django 5.2 on 2025-06-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_add_explicit_unfollow_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='default_view',
            field=models.CharField(choices=[('GALLERY', 'Gallery'), ('KANBAN', 'Kanban'), ('TABLE', 'Table')], default='GALLERY', help_text='Default view type for this board', max_length=20),
        ),
    ]
