# Generated by Django 5.2 on 2025-06-29 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_add_board_default_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='default_sort',
            field=models.CharField(choices=[('-date_uploaded', 'Date uploaded (newest first)'), ('date_uploaded', 'Date uploaded (oldest first)'), ('-date_created', 'Date created (newest first)'), ('date_created', 'Date created (oldest first)'), ('-date_modified', 'Date modified (newest first)'), ('date_modified', 'Date modified (oldest first)'), ('name', 'Name (A-Z)'), ('-name', 'Name (Z-A)'), ('-size', 'File size (largest first)'), ('size', 'File size (smallest first)')], default='-date_uploaded', help_text='Default sort order for assets in this board', max_length=30),
        ),
        migrations.AddField(
            model_name='board',
            name='kanban_group_by_field',
            field=models.ForeignKey(blank=True, help_text='Custom field to group by when using kanban view (should be a single-select field)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customfield'),
        ),
    ]
