# Generated by Django 5.2 on 2025-06-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_add_board_kanban_and_sort_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardasset',
            options={'ordering': ['order', 'added_at']},
        ),
        migrations.AddField(
            model_name='boardasset',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Manual ordering position within this board'),
        ),
        migrations.AlterField(
            model_name='board',
            name='default_sort',
            field=models.CharField(choices=[('custom', 'Custom order (drag and drop)'), ('-date_uploaded', 'Date uploaded (newest first)'), ('date_uploaded', 'Date uploaded (oldest first)'), ('-date_created', 'Date created (newest first)'), ('date_created', 'Date created (oldest first)'), ('-date_modified', 'Date modified (newest first)'), ('date_modified', 'Date modified (oldest first)'), ('name', 'Name (A-Z)'), ('-name', 'Name (Z-A)'), ('-size', 'File size (largest first)'), ('size', 'File size (smallest first)')], default='-date_uploaded', help_text='Default sort order for assets in this board', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='boardasset',
            unique_together={('board', 'asset')},
        ),
    ]
