# Generated by Django 5.2 on 2025-07-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_add_custom_sort_and_boardasset_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCheckerAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('s3_bucket', models.CharField(max_length=255)),
                ('s3_key', models.CharField(max_length=1024)),
                ('webhook_received', models.BooleanField(default=False)),
                ('results', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('use_webhook', models.BooleanField(default=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('callback_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['check_id'], name='main_assetc_check_i_d03de2_idx'), models.Index(fields=['status'], name='main_assetc_status_eacdae_idx'), models.Index(fields=['created_at'], name='main_assetc_created_e0a4ff_idx')],
            },
        ),
    ]
