# Generated by Django 5.2 on 2025-07-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_assetcheckeranalysis_ai_action_result_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiactionresult',
            name='action',
            field=models.CharField(choices=[('grammar', 'Grammar Check'), ('image_quality', 'Image Quality Check'), ('color_contrast', 'Color Contrast Analysis'), ('color_blindness', 'Color Blindness Analysis'), ('font_size_detection', 'Font Size Detection'), ('text_overflow', 'Text Overflow Detection'), ('mixed_fonts', 'Mixed Fonts Detection'), ('placeholder_detection', 'Placeholder Text Detection'), ('repeated_text', 'Repeated Text Detection')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customfieldoptionaiaction',
            name='action',
            field=models.CharField(choices=[('grammar', 'Grammar Check'), ('image_quality', 'Image Quality Check'), ('color_contrast', 'Color Contrast Analysis'), ('color_blindness', 'Color Blindness Analysis'), ('font_size_detection', 'Font Size Detection'), ('text_overflow', 'Text Overflow Detection'), ('mixed_fonts', 'Mixed Fonts Detection'), ('placeholder_detection', 'Placeholder Text Detection'), ('repeated_text', 'Repeated Text Detection')], max_length=50),
        ),
    ]
