# Generated by Django 5.2 on 2025-07-16 18:51

import main.models
import storages.backends.s3
from django.core.files.storage import storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_expand_grammar_language_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='severity',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], help_text='Severity level for AI analysis comments', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=storages['staticfiles'], upload_to=main.models.workspace_avatar_path),
        ),
    ]
