# Generated by Django 5.2 on 2025-07-17 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0030_add_comment_severity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcheckeranalysis',
            name='board',
            field=models.ForeignKey(blank=True, help_text='Board context that triggered this analysis. Null means global analysis.', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.board'),
        ),
        migrations.AddField(
            model_name='comment',
            name='board',
            field=models.ForeignKey(blank=True, help_text="Board context for this comment. Null means global 'all assets' comment.", null=True, on_delete=django.db.models.deletion.CASCADE, to='main.board'),
        ),
        migrations.AddIndex(
            model_name='assetcheckeranalysis',
            index=models.Index(fields=['board', 'status'], name='main_assetc_board_i_4ffc29_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'object_id', 'board'], name='main_commen_content_eb1b26_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['board', 'created_at'], name='main_commen_board_i_d260f1_idx'),
        ),
    ]
