# Generated by Django 5.2 on 2025-07-22 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_asset_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='Confidence score for AI-generated tags (0.0 - 1.0)', null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='Whether this tag was generated by AI analysis'),
        ),
        migrations.AddField(
            model_name='tag',
            name='source_analysis',
            field=models.ForeignKey(blank=True, help_text='The AI analysis that generated this tag', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_tags', to='main.assetanalysis'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AI_LABEL', 'AI Object/Scene Detection'), ('AI_MODERATION', 'AI Content Moderation')], default='MANUAL', help_text='Source type of this tag', max_length=20),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['workspace', 'is_ai_generated'], name='main_tag_workspa_aa532f_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['workspace', 'tag_type'], name='main_tag_workspa_19484a_idx'),
        ),
    ]
